<a href="https://colab.research.google.com/github/BhumikaGhodki/Data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

#create a 1-D array containing the value 1,2,3,4,5:

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

In [ ]:
#create 2-D array containing two arrays with the values 1,2,3 and 4,5,6
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print (arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#create a 3-D array with two 2-D arrays,both containing two array with the value 1,2,3 and 4,5,6
import numpy as np
arr = np. array([[[1,2,3],[4,5,6]],
 [[1,2,3],[4,5,6]]])
print (arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#check how many dimensions the arrays have
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#create an array with 5 dimensions and verify that it has 5 dimensions
import numpy as np
arr = np. array ([1,2,3,4],ndmin=5)
print(arr)
print('number if dimensions:', arr.ndim)


[[[[[1 2 3 4]]]]]
number if dimensions: 5


In [ ]:
#access the element on the first row,second column
import numpy as np
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row' , arr[0,1])

2nd element on 1st row 2


In [ ]:
#access the third element of the second array of the first array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [ ]:
#print the last element from the 2nd dim
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim',arr[1,-1])


last element from 2nd dim 10


In [ ]:
#slice elements from index 1 to index 5 from the following array
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])


[2 3 4 5]


In [ ]:
#from the second element ,slice element from index 1 to 4 (not include)
import numpy as np
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])


[7 8 9]


In [ ]:
#from both element return index 2;
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr [0:2,2])

[3 8]


In [ ]:
#from both element,slice index 4(not include),this will return a 2-D array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])


[[2 3 4]
 [7 8 9]]
